@startuml

scale max 600 width

title Network Example

cloud "Amazon Web Services" as AWS {
  component "Route 53 DNS"
}

cloud "Anywhere" {
  component "User Machine"
}

cloud "Corporate Data Center" as DC {
  component "Server A"
  component "Master DB"
  component "Server B"
  component "Replica DB"
}
' links
[User Machine] -up-> [Route 53 DNS]
[User Machine] --> [Server A]
[User Machine] --> [Server B]
[Server A] --> [Master DB]
[Server B] --> [Master DB]
[Master DB] --> [Replica DB]

@enduml
